# Generated by Django 4.2.5 on 2023-09-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_film_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(upload_to='photoes'),
        ),
    ]
