# Generated by Django 4.1.6 on 2023-11-16 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('feedback', models.CharField(default=None, max_length=80, null=True)),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('freelancer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.freelancer')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='film',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='film',
            name='user',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Skills',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.ManyToManyField(to='project.skills'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(to='project.skills'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback_jobs',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.freelancer'),
        ),
        migrations.AddField(
            model_name='feedback_jobs',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.jobs'),
        ),
    ]
