# Generated by Django 4.1.6 on 2023-11-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_jobs',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='project.jobs'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HireFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.freelancer')),
            ],
        ),
    ]
