# Generated by Django 4.1.6 on 2023-11-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_feedback_jobs_jobs_alter_jobs_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
